version: '3.7'

services:
  server:
    build: ./nginx-king_of_goal 
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./server:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: king_of_goal
      MYSQL_USER: admin
      MYSQL_PASSWORD: pestillo
      MYSQL_ROOT_PASSWORD: pestillo

#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    volumes:
#      - './client:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
